version: '3'

services:
  guacamole:
    restart: always
    image: guacamole/guacamole
    ports: 
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /opt/guachome
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./extensions/:/opt/guachome/extensions/

  guacd:
    restart: always
    image: guacamole/guacd
  
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080
  
volumes:
 pgdata: